language: go
go:
  - "1.12"
  - master

env:
  - GO111MODULE=on

cache:
  directories:
    - ${HOME}/source

before_install:
  - pushd ${HOME}/source
  - if [[ ! -d "./make-4.0" ]]; then
    wget http://ftp.gnu.org/gnu/make/make-4.0.tar.gz &&
    tar -vxzf make-4.0.tar.gz &&
    pushd make-4.0 && ./configure && make && popd;
    fi
  - pushd make-4.0 && sudo make install && popd
  - export PATH=${GOPATH}/bin:$PATH
  - popd
  - make --version
  - mkdir ${HOME}/.qscamel

install:
  - go get -u golang.org/x/lint/golint

script:
  - make check
  - make build
  - make test
  - make coverage
